// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBcv_9teDsAoGG6SFvktPhY8pg8mpbV0M',
    appId: '1:522052562612:web:ae67ab1d0d86a4bdfef1e1',
    messagingSenderId: '522052562612',
    projectId: 'vigo-smart-app',
    authDomain: 'vigo-smart-app.firebaseapp.com',
    storageBucket: 'vigo-smart-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjXi5MRNkoFWO_fpNfmSca3BTcMmoixjI',
    appId: '1:522052562612:android:11d6fc815bb907b0fef1e1',
    messagingSenderId: '522052562612',
    projectId: 'vigo-smart-app',
    storageBucket: 'vigo-smart-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2Xq3CdeLF-i2Vh1uOiYMzrrN9H3S0zCQ',
    appId: '1:522052562612:ios:35892a31e535e80afef1e1',
    messagingSenderId: '522052562612',
    projectId: 'vigo-smart-app',
    storageBucket: 'vigo-smart-app.appspot.com',
    iosBundleId: 'com.example.vigoSmartApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2Xq3CdeLF-i2Vh1uOiYMzrrN9H3S0zCQ',
    appId: '1:522052562612:ios:35892a31e535e80afef1e1',
    messagingSenderId: '522052562612',
    projectId: 'vigo-smart-app',
    storageBucket: 'vigo-smart-app.appspot.com',
    iosBundleId: 'com.example.vigoSmartApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBBcv_9teDsAoGG6SFvktPhY8pg8mpbV0M',
    appId: '1:522052562612:web:f673aaa0a860a108fef1e1',
    messagingSenderId: '522052562612',
    projectId: 'vigo-smart-app',
    authDomain: 'vigo-smart-app.firebaseapp.com',
    storageBucket: 'vigo-smart-app.appspot.com',
  );

}